### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asukaminato0721** [wuyudi/magic-in-ten-mins-ts#1]
- [ ] 搭配 ts-results, ts-pattern
- [ ] change open to close

> 另外指一点问题：在 ADT 那篇里，sum type 不应该用 interface 来实现吧。interface 是开的，总可以往里面增加实现的实现，而 sum type 需要是闭的。在 TS 里用 tagged union 模拟就好了

```ts
type Foo = A | B | C
// 这是闭的
interface Foo
class A implements Foo {}
class B implements Foo {}
class C implements Foo {}
// 过了三个月
class D implements Foo {}
// 这是开的
```
- [ ] monad 实现 functor 的 map 操作. 修改错误表达。 <https://stackoverflow.com/questions/45712106/why-are-promises-monads/50173415>
